spring.application.name=Product-Portal
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 Console (handy for debugging in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
#spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
#spring.security.oauth2.client.registration.google.scope=email,profile

#spring.security.oauth2.client.registration.facebook.client-id=YOUR_FACEBOOK_CLIENT_ID
#spring.security.oauth2.client.registration.facebook.client-secret=YOUR_FACEBOOK_CLIENT_SECRET
#spring.security.oauth2.client.registration.facebook.scope=email,public_profile


jwt.secret=mySuperSecretKeyThatIsAtLeast32CharsLong123!
rentmy.api.key=your-real-api-key

